export default interface Etablissement {
  id: number
  siren: string
  siret: string
  nic: string
  l1_normalisee: string
  l2_normalisee: string
  l3_normalisee: string
  l4_normalisee: string
  l5_normalisee: string
  l6_normalisee: string
  l7_normalisee: string
  l1_declaree: string
  l2_declaree: string
  l3_declaree: string
  l4_declaree: string
  l5_declaree: string
  l6_declaree: string
  l7_declaree: string
  numero_voie?: string
  indice_repetition: string
  type_voie: string
  libelle_voie: string
  code_postal: string
  cedex: string
  region: string
  libelle_region: string
  departement: string
  arrondissement: string
  canton: string
  commune: string
  libelle_commune: string
  departement_unite_urbaine: string
  taille_unite_urbaine: string
  numero_unite_urbaine: string
  etablissement_public_cooperation_intercommunale: string
  tranche_commune_detaillee: string
  zone_emploi: string
  is_siege: string
  enseigne: string
  indicateur_champ_publipostage: string
  statut_prospection: string
  date_introduction_base_diffusion: string
  nature_entrepreneur_individuel: string
  libelle_nature_entrepreneur_individuel: string
  activite_principale: string
  libelle_activite_principale: string
  date_validite_activite_principale: string
  tranche_effectif_salarie?: string
  libelle_tranche_effectif_salarie: string
  tranche_effectif_salarie_centaine_pret: string
  date_validite_effectif_salarie?: string
  origine_creation: string
  date_creation: string
  date_debut_activite: string
  nature_activite: string
  lieu_activite: string
  type_magasin: string
  is_saisonnier: string
  modalite_activite_principale: string
  caractere_productif: string
  participation_particuliere_production: string
  caractere_auxiliaire: string
  nom_raison_sociale: string
  sigle: string
  nom: string
  prenom: string
  civilite: string
  numero_rna: string
  nic_siege: string
  region_siege: string
  departement_commune_siege: string
  email: string
  nature_juridique_entreprise: string
  libelle_nature_juridique_entreprise: string
  activite_principale_entreprise: string
  libelle_activite_principale_entreprise: string
  date_validite_activite_principale_entreprise: string
  activite_principale_registre_metier: string
  is_ess: string
  date_ess: string
  tranche_effectif_salarie_entreprise: string
  libelle_tranche_effectif_salarie_entreprise: string
  tranche_effectif_salarie_entreprise_centaine_pret: string
  date_validite_effectif_salarie_entreprise: string
  categorie_entreprise: string
  date_creation_entreprise: string
  date_introduction_base_diffusion_entreprise: string
  indice_monoactivite_entreprise: string
  modalite_activite_principale_entreprise: string
  caractere_productif_entreprise: string
  date_validite_rubrique_niveau_entreprise_esa: string
  tranche_chiffre_affaire_entreprise_esa: string
  activite_principale_entreprise_esa: string
  premiere_activite_secondaire_entreprise_esa: string
  deuxieme_activite_secondaire_entreprise_esa: string
  troisieme_activite_secondaire_entreprise_esa: string
  quatrieme_activite_secondaire_entreprise_esa: string
  nature_mise_a_jour: string
  indicateur_mise_a_jour_1: string
  indicateur_mise_a_jour_2: string
  indicateur_mise_a_jour_3: string
  date_mise_a_jour: string
  created_at: string
  updated_at: string
  longitude: string
  latitude: string
  geo_score: string
  geo_type: string
  geo_adresse: string
  geo_id: string
  geo_ligne: string
  geo_l4: string
  geo_l5: string
}
